# copy.yml

  - name: copy scripts files to remote server
    copy:
      src: jenkins/scripts/deploy/{{item}}
      dest: ~/
      with_items:
        ['admin-start.sh','deploy.sh']

  - name: copy jar file to remote server
    copy:
      src: target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar
      dest: ~/poc 
